### PR TITLE
Subscription read

### PR DESCRIPTION
**Pull request by cap10morgan**
I needed a subscription read handler for election-notification-http-api, so this PR adds it.

### CODE REVIEW

**Comment by tank157** [comment]
This all looks good, we'll have a bit of a merge conflict with the work I just PR'd, but we can cross that bridge when we need to. Was it checked out in krakenstein?

**Comment by cap10morgan** [comment]
@tank157 Yep, worked in krakenstein.

**Comment by cap10morgan** [comment]
@tank157 Is this OK to merge, or should I leave that for you to coordinate with your other PR?

**Comment by tank157** [comment]
I figured the "this all looks good to me" would have sufficed to answer that, but yes.

**Pull request merged**
