### PR TITLE
added "and the rest of the TurboVote team" after signers

### PR DESCRIPTION
**Pull request by kep**
Changed based on recommendation from user testing; without context, users do not understand who the three names belong to.

### CODE REVIEW

**Comment by cap10morgan** [comment]
Yes! I have long wanted to see this brought over from classic.

Nittiest of nitpicks: Does it need to be in parentheses? "Matt, Dave, Kathryn, and the rest of the TurboVote team" seems more straightforward and would just be:

```clojure
(apply format "%s, %s, %s, and the rest of the TurboVote team"
                                   (util/signer-names))
```

**Comment by kep** [comment]
SGTM, if you want to make that edit. If you do, can we keep the & for
"and"? I like the curlicue.

**Comment by cap10morgan** [comment]
Yeah, I'll keep the &. :)

**Comment by cap10morgan** [comment]
OK, that's pushed. Along w/ a centralization of the code that generates that string (so we only have to change it in once place in the future) and an updating of the list of signer names that the system chooses 3 random elements from.

**Comment by ddellacosta** [comment]
LGTM

**Pull request merged**
